app/reporting/components/observation/directives/workflow.js
shared/partials/aside.html

But still missing observation in scope

Hotfixing with aside template deleted by mistake

---

app/reporting/app.js
app/reporting/components/main/startPage.html
app/reporting/components/observation/1.html
app/reporting/components/observation/controllers/ObservationController.js
app/reporting/components/observation/directives/workflow.html
app/reporting/index.html
shared/resolve/app.js
shared/resolve/club.js
shared/resolve/service.js
shared/resolve/username.js

Testing a shared module with directives to easily resolve a name from an id ie resolve a users name from id

Resolve usernames, clubs etc by id

---

app/reporting/components/component/directives/observationComponents.js
app/reporting/components/observation/directives/filepreviews.js
app/reporting/components/observation/directives/involvedpersonselector.js
app/reporting/components/observation/directives/organization.js
app/reporting/components/observation/directives/summary.js
app/reporting/components/observation/directives/workflow.js

Updated all directives using aside to support aside with browser back button aside.hide

---

app/reporting/components/observation/1.html
app/reporting/components/observation/directives/organization.html
app/reporting/components/observation/directives/organizationSummary.html

Layout and pilot to organisation

---

app/profile/app.js
app/profile/index.html
app/profile/routes.js
app/reporting/components/location/locationService.js
app/reporting/components/main/mainController.js
app/reporting/components/main/startPage.html
app/reporting/components/observation/controllers/ObservationController.js
app/reporting/components/observation/directives/clubselector.js
app/reporting/components/observation/directives/filepreviews.html
app/reporting/components/observation/directives/locationselector.html
app/reporting/components/observation/directives/locationselector.js
app/reporting/components/observation/directives/observationdateselector.js
app/reporting/components/observation/directives/watchers.js
app/reporting/components/observation/directives/weather.html
app/reporting/components/observation/directives/workflow.html
app/reporting/components/observation/directives/workflow.js
app/reporting/components/observation/services/ObservationService.js
app/reporting/shared/services/RestService.js
shared/resolve/user.js

Closes #96 
- observation instantiated to allow correct registring in startpage
- correct datetime for datetimepicker
- default club for clubselector
- ng-if wait for observation before calling directives
- using $rootScope for loadObservation

Misc enhancements

---

app/users/app.js
app/users/index.html
app/users/partials/main.html
app/users/partials/user.html
app/users/routes.js

Currently only lists and resolves users

Added simple user management app

---

static/css/app.css

Might fix #126 
The html, body { padding-top... gave a double padding

Removed html from padding-top

---

shared/filters/nl2br.js
static/js/angled/template.html

Missing nl2br filter after chaning files

Hotfix v0.2.1

---

app/obs/components/component/directives/observationComponent.html
app/obs/components/component/directives/observationComponentSummary.html
app/obs/components/component/directives/observationComponents.html
app/obs/components/observation/controllers/ObservationController.js
app/obs/components/observation/controllers/ReportController.js
app/obs/components/observation/directives/workflow.js
shared/directives/inlinehelp.js
shared/resolve/user.js
static/css/app.css
static/js/angled/template.html

Multiple fixes

---

app/obs/components/main/mainController.js
app/obs/components/observation/controllers/ReportController.js
app/obs/components/observation/controllers/SearchController.js
app/obs/components/observation/directives/observationHfkSelector.html
app/obs/components/observation/directives/observationHfkText.html
app/obs/components/observation/report.html
shared/auth/loginServices.js

- Updated report view
- Updated ask/hfk directive
- Using ORS in navbar
- Auth directive to show error if no response with backend

Misc fixes and tweaks

---

CHANGELOG
app/obs/components/observation/directives/observationHfkSelector.html
app/obs/components/observation/report.html

- using nl2br filter for ask.text fields
- readonly for buttons in report view
- added changelog skeleton file (AEH request)

Additional fixes

---

app/users/index.html
app/users/partials/main.html

Modified users app to adhere to npm and grunt

---

shared/resolve/user.js

Matches backends list of unique jumpers

Added the new resolver for negative id's from anon list in backend

---

app.js
applications.json
index.html
shared/services/Appswitcher.js

Cchanged from $location to window.location to be able to parse root

Added snakeoil to frontpage and app

---

app/obs/observation/controllers/ObservationController.js
app/obs/observation/controllers/ReportController.js
app/obs/observation/directives/workflow.html
app/obs/observation/directives/workflow.js
app/obs/observation/directives/workflowButton.js
app/obs/observation/services/ObservationService.js
shared/partials/toolbar.html

Remove all tooltips from toolbar and workflow dialog

---

app/obs/component/directives/observationComponentSummary.js
shared/directives/tagtypeahead.html
shared/directives/tagtypeahead.js
shared/services/RestService.js

Adding new cause or consequence when leaving text-input instead of waiting for (+).
Also no longer capitalizing users input while user is still typing

Component new cause and typeahead fix

---

app/obs/component/directives/observationComponent.html
app/obs/component/directives/observationComponentSummary.html

Barrier can be used in combination with cause, consequence or incident

Enabling sensible handling of safety-barrier component flag again.

---

bower.json
static/css/app.css

This caused double height of the tagging textarea

Width of tagging input element was set to width of parent.

---

app/obs/index.html
app/obs/persondetails/directives/involvedperson.html
bower.json
shared/directives/singlepersonselector.html
shared/directives/singlepersonselector.js
shared/resolve/service.js
shared/resolve/user.js
static/css/app.css

Use upgraded ui-select library to create singlepersonselector.
This enables adding non-members as riggers in persondetails

Improved person selector

---

app/obs/observation/directives/organization/organization.html
shared/directives/multipersonselector.html
shared/directives/multipersonselector.js
static/css/app.css

Organization editor working again

Multipersonselectors was not showing when model was not inited

---

shared/auth/loginServices.js
shared/auth/views/login.html

Oauth2 support to corresponding fnlf-backend implementation

Feature oauth

---

app/obs/component/directives/observationComponentsSummary.html
app/obs/component/directives/observationComponentsSummary.js

Still need to insert the incident-component after the last cause. But at least the new component dialog is shown

Show new incident box if no incident component

---

Gruntfile.js
app/obs/component/directives/observationComponent.html

Feature show all involved in component

---

shared/auth/loginServices.js
shared/auth/views/login.html

Remove melwin login

---

app/obs/component/directives/flagseditor.html
app/obs/search/directives/searchfilters.html
app/obs/search/search.html

Fix search
